### ISSUE TITLE
Yarn 2 / PnP support?

### ISSUE THREAD

**Issue by dpeek** [vercel/ncc#545]
So I am being super dev hipster and testing out Yarn 2, and it seems like no required modules are being included in the compiled file at all – no warnings, no errors, just the files in src and nothing else :)

This might be what I get for being bleeding edge, but wanted to check if this was a known issue (I couldn't find anything in the issues around Yarn 2) before I start testing locally to figure out what is going on.

For reference Webpack requires a plugin to support PnP resolves: https://www.npmjs.com/package/pnp-webpack-plugin

**Comment by ofhouse** [comment]
Since ncc is based on the upcoming `webpack@5` it should not need a plugin for PnP because the next version of webpack supports PnP out of the box.
Unfortunately the webpack version that ncc uses is a bit aged (`webpack@5.0.0-alpha.17`) and PnP support was added (if I am correct) in `5.0.0-alpha.20`.

Unsure if the team accepts a PR for bumping the webpack version to the latest beta, but would love to see when it gets an update 😇

**Comment by dpeek** [comment]
Thanks for that information. I switched off PnP for now but will test locally with upgraded we pack dependency and see how many errors I get :)
