### ISSUE TITLE
Support for Webpack 5

### ISSUE THREAD

**Issue by leerob** [vercel/ncc#680]
- https://twitter.com/soytxemaleon/status/1377994900101341184
- https://nextjs.org/docs/messages/webpack5

**Comment by guybedford** [comment]
We've been keeping ncc up-to-date against Webpack 5 as this has been crucial to ensuring the ES module interop behaviours work out. The latest update was a couple of weeks ago. I've just posted https://github.com/vercel/ncc/pull/681 as well to ensure we're at latest for the next release.

Experimenting with more agressive optimization options in https://github.com/vercel/ncc/blob/master/src/index.js#L230 could be worth looking into. Since ncc focuses on making things work first and foremost, setting these options too agressively might be risky though.

**Comment by styfle** [comment]
Closing since we are currently using the latest webpack (5.30.0)
