### ISSUE TITLE
Upgrade from 0.30.0 to 0.31.1 breaks dynamic import

### ISSUE THREAD

**Issue by louisgv** [vercel/ncc#793]
I have some express route that I'm dynamically importing using the snippet below:

```
import { Router } from "express"

const routeModulePaths = [
  "auth",
  "user",
  "ping",
  // 30+ more routes
]

export const setupApiRoutes = async () => {
  const router = Router()

  await Promise.all(
    routeModulePaths.map((path) =>
      import(`./${path}`).then((m) => router.use("/", m.default))
    )
  )

  return router
}

```

ncc@0.30.0 worked, the dist contains multiple index.js files (18.index.js, 276.index.js, etc...), which I assumed was ncc splitting the bundles.

ncc@0.31.1 didn't work. It produces a single index.js file, and upon running it throws this error:

> Cannot find module './auth'
> Require stack:
> - /app/dist/index.js Error: Cannot find module './auth'

I wonder if the change to how tsconfig is further leveraged on the bundling process has anything to do with this :-?...

**Comment by paulrberg** [comment]
The same issue has caused a bug in my tool [create-eth-app](https://github.com/paulrberg/create-eth-app):

https://github.com/paulrberg/create-eth-app/issues/175

I'm copying a file called `gitignore` only if some condition is met:

https://github.com/paulrberg/create-eth-app/blob/fa2d2771f264a4767ed8617b07e89285d9c24159/src/createEthApp.ts#L93

Because the copy operation depends upon an if block, I take it that ncc doesn't bundle the `gitignore` file in the build dir. But I think this is confusing - ncc should optimistically look for all dynamical paths and add them to the bundle. Or at the very least it should give us a flag to enable this behavior back.

**Comment by styfle** [comment]
If you have multiple `tsconfig.json` files, then perhaps the `walkParentDirs()`from https://github.com/vercel/ncc/pull/770 is detecting the wrong config?

**Comment by louisgv** [comment]
For my project, I have moved my import to statically analyzable import, which allowed ncc to find and bundle the modules:

```
import { Router } from "express"

const routeModules = [
  import("auth"),
  import("user"),
  import("ping"),
  // 30+ more routes
]

export const setupApiRoutes = async () => {
  const router = Router()

  await Promise.all(
    routeModules.map((mod) =>
      mod.then((m) => router.use("/", m.default))
    )
  )

  return router
}

```

A quick write up: https://dev.to/louisgv/typescript-dynamic-module-import-2dln

**Comment by paulrberg** [comment]
> If you have multiple `tsconfig.json` files, then perhaps the `walkParentDirs()`from #770 is detecting the wrong config?

I don't have multiple `tsconfig.json` files. Maybe @louisgv has?

>  I have moved my import to statically analyzable import

Thanks for posting an update with the solution you found :)

**Comment by louisgv** [comment]
I do have multiple tsconfig.json in my monorepo but the bundle only run under one leaf config (that extend root config)
