### ISSUE TITLE
fix: No extra files should be generated

### ISSUE THREAD

**Issue by wll8** [vercel/ncc#893]
I want to output only one file, I can't find any other configuration to accomplish this.

## replay

index.js
``` js
#!/usr/bin/env node

const shelljs = require('shelljs');
shelljs.exec(`echo hello word~`)
```

``` sh
>npx ncc build src/index.js -o xx 
ncc: Version 0.33.3
ncc: Compiling file index.js into CJS
  1kB  xx\exec-child.js
191kB  xx\index.js
192kB  [631ms] - ncc 0.33.3

>npx shx ls xx
exec-child.js
index.js
```

It outputs two files:
- exec-child.js
- index.js

## env
- node v14.15.5
- ncc v0.33.3
- os win10x64

**Comment by styfle** [comment]
The `exec-child.js` file is not considered a normal source file since its not imported/required. Instead, its considered an asset because is executed here https://github.com/shelljs/shelljs/blob/003a39d652039f2171aca66770d1d7326dd3b216/src/exec.js#L80-L100

I don't think this code would work if `exec-child.js` was bundled, it needs to remain a separate file.
