### ISSUE TITLE
Cannot use ncc with "sharp"

### ISSUE THREAD

**Issue by leonardoventurini** [vercel/ncc#991]
This is the error I get:

<img width="837" alt="image" src="https://user-images.githubusercontent.com/17411182/197372108-da11014f-5093-4d6a-a941-110efee66181.png">

I ran it on both arm64/amd64, same thing.

Any ideas?

**Comment by ueoeae** [comment]
Pretty sure it's because sharp has native components (C++ binaries).

**Comment by leonardoventurini** [comment]
Yes, I imagined. I solved it for me by making it an external dependency and creating an external runtime `package.json` in Docker with only that package.

**Comment by abcfy2** [comment]
You have to install `sharp` use official prebuilt with static linked `libvips`. E.g: `SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install`, see: https://sharp.pixelplumbing.com/install#aws-lambda, then use ncc. Otherwise your `dist/` only work in your local environment because it's dynamic linked, you cannot copy `dist/` to other machine to make it running.

I also use sharp and I have this issue: https://github.com/vercel/ncc/issues/744
